### PR TITLE
Change existsPredicates to Unicode in predicates.py

### PR DESCRIPTION
**Pull request by xykev**
This was giving me the error

TypeError: sequence item 1: expected string or Unicode, int found

### CODE REVIEW

**Comment by xykev** [comment]
Hm...not sure why the Travis CI build failed. I am running on Windows if that might be an issue?

**Comment by fgregg** [comment]
You need to update the tests.

**Comment by xykev** [comment]
How would I do that? Sorry, I'm new to gitHub...

**Comment by fgregg** [comment]
No problem. See the developer instructions here: https://github.com/datamade/dedupe#developers to get tests running on your local machine. 

Then fix the tests under the test directory. Once the tests pass locally, commit changes to the tests and push to github.

**Comment by fgregg** [comment]
Closed by f267b6341e0a6c60c037064362f98caf9f14479b

**Pull request closed without merging**
