### PR TITLE
Use raw_input to help with input errors in jupyter notebook

### PR DESCRIPTION
**Pull request by nateyoder**
Fallback to using input in python3.

Created based off my issues and #478

### CODE REVIEW

**Comment by fgregg** [comment]
Sorry, I don't want to take on the responsibility for support jupyter

**Comment by nateyoder** [comment]
Fair enough but I really think this is just best practice when dealing with Python2 and Python3: http://stackoverflow.com/questions/21731043/use-of-input-raw-input-in-python-2-and-3

That said I'm happy to maintain my own fork :)  Thanks for a great package.

**Comment by fgregg** [comment]
Hmm, didn't know this was a python 2/3 issue.

 I would accept this http://stackoverflow.com/a/38691215/98080

**Comment by fgregg** [comment]
Nevermind, that's already what I'm doing, haha. Good luck.

**Comment by nateyoder** [comment]
Yeah I believe that is what you had but at least for me that doesn't actually work.

**Comment by fgregg** [comment]
Strangely, python-future should do exactly what your PR did. https://github.com/PythonCharmers/python-future/blob/master/src/future/builtins/misc.py#L57

You could open up an issue there to figure out why it didn't.

**Pull request closed without merging**
